### ISSUE TITLE
Extender works wrongly when I compare List.Count and another variable

### ISSUE THREAD

**Issue by sh2ezo** [Dreamescaper/IntelliSenseExtender#26]
Hello!

I have an instance of List and I also have some variable. When I need to compare List.Count with variable and I write "<", Extender suggests a types, though I need a variables. I think, this is going on because List is derived from IEnumerable and IEnumerable has extension method Count<T>.

![image](https://user-images.githubusercontent.com/1949160/40575541-6e2d9486-60ef-11e8-9dec-38d024ce1e07.png)

I think, in such cases (type has fields and methods with same names), You can suggest variables and types.

**Comment by Dreamescaper** [comment]
So you don't have _maxAllowedTasks suggestion at all?
That's really strange, because that's native VS functionality, not from extension.
I have an item to infer type on such cases, so suitable items would be suggested first. 
But anyway variable suggestion should be always present, I haven't changed anything there.

Would you be able to send project where it happens?

**Comment by sh2ezo** [comment]
> That's really strange, because that's native VS functionality, not from extension
After this words tried to disable extension and variable did not appear again

On this week I upgraded my VS2017 to 15.7.2. And I don't remember I wrote code like that after upgrade (compare List.Count and variables). Can VS be broken after upgrade?

**Comment by Dreamescaper** [comment]
Don't know, cannot reproduce that (neither with 15.7.2, nor with 15.8.0 Preview).

**Comment by Dreamescaper** [comment]
Tested your example. 
You're absolutely right - that's due to Linq method Count() - I cannot reproduce that with missing Linq using.
Still, that's Roslyn issue, not IntelliSense Extender.
