### ISSUE TITLE
Does not work with VS 2017 V15.6.4

### ISSUE THREAD

**Issue by vknht** [Dreamescaper/IntelliSenseExtender#28]
Hello,

like the Title says, the Extension does not work with Version 15.6.4.
It used to work with previous Versions.
Re-Installing did not help.

![v15 6 4](https://user-images.githubusercontent.com/34534652/42820475-8f8381a8-89d6-11e8-98b1-c85c19cfe523.png)

**Comment by Dreamescaper** [comment]
Do you have ability to update to latest version (15.7.5)?

Unfortunately, I cannot test it ATM on your version. Usually I try to check that everything on latest release and on latest preview before submitting to marketplace.
And due to some amount of undocumented hacks used it might not work with older versions.

Unless it's something not version related, of course. Is there any error messages, logs, etc?

**Comment by vknht** [comment]
Note to self: Update before claiming it does not work...

Newest Version is working. Sorry for the trouble.
