### ISSUE TITLE
Visual studio hangs

### ISSUE THREAD

**Issue by berhalak** [Dreamescaper/IntelliSenseExtender#32]
Visual studio 2017 hangs on this code:
```
namespace ConsoleApp50
{
    class Program
    {
        static void Main(string[] args)
        {
        }

        public object this[string key]
        {
            get
            {
                return null;
            }
            set
            {
                this.name = // start tapping value and hangs
            }
        }
    }
}
```

**Comment by Dreamescaper** [comment]
Looking...

**Comment by Dreamescaper** [comment]
@berhalak 

Fixed in latest master. I need to fix several things before pushing it to Marketplace, but you can get VSIX from latest appveyor build if it bothers you a lot.
Thanks for reporting!

https://ci.appveyor.com/api/buildjobs/l1g0kichtnnfte36/artifacts/IntelliSenseExtender%2Fbin%2FRelease%2FIntelliSenseExtender.vsix
