### ISSUE TITLE
Missing suggested types

### ISSUE THREAD

**Issue by SirRufo** [Dreamescaper/IntelliSenseExtender#39]
When you have a **fresh started** Visual Studio and create a new project, then some classes are not suggested:

![2018-12-02 13_25_55-newproject](https://user-images.githubusercontent.com/6330968/49339723-4882d200-f636-11e8-888c-6d2490f1e1f5.png)

After closing the solution and open it again everything works as expected

![2018-12-02 13_34_18-oldproject](https://user-images.githubusercontent.com/6330968/49339789-11f98700-f637-11e8-8550-95ec38c7042a.png)

Opening an existing solution with a **fresh started** Visual Studio is no problem. Once you got IntelliSenseExtender running then you can create new projects and everything works fine.

**Comment by Dreamescaper** [comment]
Thanks for reporting issue, it is fixed in latest master! 

I'd still like to fix couple of things before updating it on Marketplace, but if it bothers you a lot, you could get it from latest Appveyor build:
https://ci.appveyor.com/api/buildjobs/4mhaxgh0dgdb03th/artifacts/IntelliSenseExtender%2Fbin%2FRelease%2FIntelliSenseExtender.vsix

**Comment by SirRufo** [comment]
Now after a fresh start and opening an **existing** Solution it does not suggest all types.
After close and open again everything is fine again.

**Comment by Dreamescaper** [comment]
That's strange.
Will take a look later

**Comment by Dreamescaper** [comment]
Are you able to reproduce that constantly? Could you share exact STR?
Simply open visual studio -> open existing project?

**Comment by Dreamescaper** [comment]
Sure, let me know!
