### ISSUE TITLE
Cannot select overloads

### ISSUE THREAD

**Issue by matej-zajacik** [Dreamescaper/IntelliSenseExtender#61]
Hey there!

![image](https://user-images.githubusercontent.com/8986611/57007261-93a21080-6be7-11e9-8d34-2556b31da484.png)

In the above example, when you type `Method(`, or `Meth`, then press `Enter`, then you type `(`, the focus is put on the autocompletion list, which prevents selecting all the overloads by pressing up and down arrows on your keyboard.

With the extension disabled, this works normally: you can select overloads first...

![image](https://user-images.githubusercontent.com/8986611/57007365-52f6c700-6be8-11e9-8937-8998049de0d4.png)

...and only when you start typing, the autocompletion list shows up with suggested values for parameters.

The former behavior forces you to use mouse to click those little arrows, which is much slower, of course.

Anyway, thank you very much for this wonderful tool!

**Comment by matej-zajacik** [comment]
Note: The issue goes away when you disable options in the `Object Creation` section. So it's perfectly okay for me, but I'm not sure if this is intended behavior.

**Comment by Dreamescaper** [comment]
That was intended to work with locals and 'new' completions.
The point is to invoke intellisense completion in methods automatically, so that you would be able to select suggested option straight away.

Something like that:
![2019-05-07_12-36-54](https://user-images.githubusercontent.com/17177729/57289860-dfabf400-70c4-11e9-859c-3f649aea170f.gif)

So that's expected, that arrow keys work for suggestions dialog. You can press ESC, and then focus will be switched back to override selection.

Still, if you don't like that behavior - you can disable option 'Invoke IntelliSense automatically' in 'Object Creation' section (or disable the whole section, as you did, if you don't need those suggestions at all).

**Comment by matej-zajacik** [comment]
All right. Thank you for the explanation!
